// Automatically generated by @svgr, do not edit directly! See icon/icon-index-template
import '../styles.less';
import { IconListType } from '../interface';
import { default as PromotionRocket } from './PromotionRocket';

const Icons:any = {
  PromotionRocket
};

const IconList: IconListType = [ 'PromotionRocket' ];

type IconNamesType = 'PromotionRocket';

export { Icons, IconList };
export type { IconNamesType };
